### ISSUE TITLE
Does not always run

### ISSUE THREAD

**Issue by moisesrodriguez** [delivered/attach-to-trello-card-action#3]
I have this action set for pull request: open, reopened, edited

```
name: Attach to Trello
on:
  pull_request:
    types: [opened, reopened, edited]
jobs:
  attach-trello:
    runs-on: ubuntu-latest
    name: Find trello link and attach to card
    steps:
      - uses: delivered/attach-to-trello-card-action@master
        with:
          trello-key: ${{ secrets.TRELLO_KEY }}
          trello-token: ${{ secrets.TRELLO_TOKEN }}
```

However, I've had times that a pull request is opened and the action does not run. I have to edit it to have it run. Other times it runs but it fails as if it does not find a Trello link, but the link is there. Again what I do is edit it and then it runs successfully. 

Any ideas why this might be happening?
